### ISSUE TITLE
more simulated vagrant up

### ISSUE THREAD

**Issue by joestein** [CiscoCloud/microservices-infrastructure#256]
It would be great to have vagrant up more simulate networked data centers. Should have configurable amount of data centers, within each data center (virtual ip e.g. https://github.com/mesos/kafka/blob/master/src/vagrant/Vagrantfile#L18 ) configurable amount of masters and slaves. The defaults for each would be == 1. This way we can test and launch on the two different services the clusters and operations between them more succinctly from our host machine or just role a single instance.

**Comment by altvnk** [comment]
It would be great! I also think that in Vagrant config we can have more realistic sandbox with network interaction.
For now i working on dynamic box loading from YAML like this:

```YAML
---
  :master:
    count: 3
    mem: 256
    cpus: 1
    ipbase: "172.31.1."
  :slave:
    count: 2
    mem: 512
    cpus: 1
    ipbase: "172.31.2."
-- cut --
```
My realisation uses two network adapters on each box: one NAT and one Host-only so no any port-forwarding is needed. Vagrant even can add records to hosts file via plugin.
So in few days i can be able to make PR or show gist for review with my changes. One thing that is not done for now is multi-dc simulation.
