### ISSUE TITLE
Removing 127.0.0.1 localhost from host file cause problems

### ISSUE THREAD

**Issue by TeaBough** [CiscoCloud/microservices-infrastructure#689]
I have a vagrant cluster with 3 leaders and when `consul-wait-for-leader.sh` is run it says that `No Consul leader elected in 30 seconds`, it is because it tries to curl `localhost:8500` the problem is that it can't resolv localhost since it has been remove by the common role. I dont' understand why we do this :

```
- name: clean hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^127\.0\.0\.1(\s+){{ inventory_hostname }}.*'
    - '^::1(\s+){{ inventory_hostname }}.*'
```
