### ISSUE TITLE
Communication between container from different hosts

### ISSUE THREAD

**Issue by TeaBough** [CiscoCloud/microservices-infrastructure#700]
I have 2 vagrant machines (`hostA`, `hostB`), `hostA` contains `containerA` and the `hostB` contains  `containerB`.

Here is what works : 
on `hostA` I can ping `containerA`
on `hostB` I can ping `containerB`

Here is what doen't work :
on `hostA` I can't ping `containerB`
on `hostB` I can't ping `containerA`
on `containerA` I can't ping `containerB`
on `containerB` I can't ping `containerA`

Has anyone any clue why all the above cases are not working ?

**Comment by stevendborrelli** [comment]
@TeaBough do you have a vangrantfile we can use to duplicate your test env?

**Comment by TeaBough** [comment]
yep : 
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

def load_security
  fname = File.join(File.dirname(__FILE__), "security.yml")
  if !File.exist? fname
    $stderr.puts "security.yml not found - please run `./security-setup` and try again."
    exit 1
  end

  YAML.load_file(fname)
end

num_worker_instance=3
num_master_instance=3

# VAGRANT_PRIVATE_IP = "192.168.242.55"

Vagrant.configure(2) do |config|
  config.vm.box = "CiscoCloud/microservices-infrastructure"

  config.vm.provider:virtualbox do |vb|
    vb.auto_nat_dns_proxy = false
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off' ]
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off' ]
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm',:id, '--cpus', 1]
    vb.customize ['modifyvm',:id, '--memory', 1536]
  end

  config.ssh.forward_agent = true
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.insert_key = false

  (1..num_master_instance).each do |i|
    config.vm.define "master#{i}" do |v|
      v.vm.network "private_network", ip: "192.168.30.5#{i}"
      v.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
      v.vm.hostname = "master#{i}"
      v.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
    end
  end

  (1..num_worker_instance).each do |i|
    config.vm.define "worker#{i}" do |v|
      v.vm.network "forwarded_port", guest: 22, host: 2210+i, id: "ssh", auto_correct: true
      v.vm.network "private_network", ip: "192.168.31.5#{i}"
      v.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
      v.vm.hostname = "worker#{i}"
      v.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
    end
  end
end
```

And here is my playbook : 
```
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check for security
      when: security_enabled is not defined or not security_enabled
      fail:
        msg: |
          Security is not enabled. Please run `security-setup` in the root
          directory and re-run this playbook with the `--extra-vars`/`-e` option
          pointing to your `security.yml` (e.g., `-e @security.yml`)

- hosts: all
  pre_tasks:
    - name: set vagrant ip addresses in inventory
      set_fact:
        private_ipv4: "{{ vagrant_private_ipv4 }}"
        public_ipv4: "{{ vagrant_private_ipv4 }}"
  vars:
    consul_dc: vagrant
    consul_acl_datacenter: vagrant
    provider: vagrant
    remote_user: vagrant
    consul_dns_domain: consul
    consul_servers_group: role=control
  roles:
    - { role: common, tags: ['common'] }
    - { role: collectd, tags: ['collectd'] }
    - { role: logrotate, tags: ['logrotate'] }
    - { role: consul-template, tags: ['consul-template'] }
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - consul
    - etcd
    - dnsmasq

- hosts: role=worker
  gather_facts: no
  vars:
    provider: vagrant
    remote_user: vagrant
    consul_dc: vagrant
    consul_dns_domain: consul
    mesos_mode: follower
  pre_tasks:
    - name: set vagrant ip addresses in inventory
      set_fact:
        private_ipv4: "{{ vagrant_private_ipv4 }}"
        public_ipv4: "{{ vagrant_private_ipv4 }}"
  roles:
    - calico
    - mesos
    - haproxy

- hosts: role=control
  gather_facts: no
  pre_tasks:
    - name: set vagrant ip addresses in inventory
      set_fact:
        private_ipv4: "{{ vagrant_private_ipv4 }}"
        public_ipv4: "{{ vagrant_private_ipv4 }}"
  vars:
    provider: vagrant
    remote_user: vagrant
    consul_dns_domain: consul
    consul_dc: vagrant
    consul_servers_group: role=control
    mesos_leaders_group: role=control
    mesos_mode: leader
    zookeeper_server_group: role=control
  roles:
    - vault
    - zookeeper
    - mesos
    - marathon
```
