### ISSUE TITLE
Ansible is depreciating nova keypair

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#80]
Regarding:
https://github.com/CiscoCloud/microservices-infrastructure/blob/master/openstack/provision-nova-key.yml

Ansible is depreciating nova keypair in favor of os_keypair in 1.9

https://github.com/ansible/ansible-modules-core/commit/cae8241ea71abfa5e57f5557bb98448badfbca61

**Comment by keithchambers** [comment]
Once [Terraform](https://github.com/hashicorp/terraform) supports multiple providers in a single template  and once the [OpenStack provider](https://github.com/hashicorp/terraform/pull/924) is merged we plan to switch from provisioning with Ansible to provisioning with Terraform.

Near term I'm thinking we could add logic like this:
```
---
- include: verify-env.yml

- hosts: all
  connection: localhost
  gather_facts: no
  tasks:
    - name: add ssh key to openstack tenant (when ansible_version < 1.9)
      local_action:
        module: nova_keypair
        name: "{{ ansible_ssh_key }}"
        public_key: "{{ ansible_ssh_pubkey }}"
        auth_url: "{{ os_auth_url }}"
        login_username: "{{ lookup('env','OS_USERNAME') }}"
        login_password: "{{ lookup('env','OS_PASSWORD') }}"
        login_tenant_name: "{{ os_tenant_name }}"
        state: present
        when: ansible_version | version_compare('1.9', '<')

    - name: add ssh key to openstack tenant (when ansible_version >= 1.9)
      local_action:
        module: os_keypair
        name: "{{ ansible_ssh_key }}"
        public_key: "{{ ansible_ssh_pubkey }}"
        auth_url: "{{ os_auth_url }}"
        login_username: "{{ lookup('env','OS_USERNAME') }}"
        login_password: "{{ lookup('env','OS_PASSWORD') }}"
        login_tenant_name: "{{ os_tenant_name }}"
        state: present
        when: ansible_version | version_compare('1.9', '>=')
```

Thoughts?
