### ISSUE TITLE
Docker Persistent Volume Support via Mesos/ Marathon (+ Ceph)

### ISSUE THREAD

**Issue by vanthome** [CiscoCloud/microservices-infrastructure#853]
Docker 1.9 allows usage of storage drivers. Mesos also supports management of persistent storage resources. Mantl should expose this functionality. Preferrably through ceph. There is a driver for docker already [1].

[1] https://docs.docker.com/registry/storage-drivers/rados/

**Comment by stevendborrelli** [comment]
@vanthome adding this to our feature backlog. 

1. Support Ceph, either via Kubernetes https://github.com/kubernetes/kubernetes/tree/master/examples/rbd or Mesos https://github.com/Intel-bigdata/ceph-mesos
2. Docker 1.9 support is probably 1-2 months away in CentOS

**Comment by abn** [comment]
@stevendborrelli +1 on this; what would be the most useful thing for us to do to help this along? Definitely have a need for this and looking at ceph-mesos at the moment as we do not use Kubernetes atm.

**Comment by stevendborrelli** [comment]
@abn we're still blocked on CentOS's docker version at 1.8..2 for this and docker networking. We may have to move over to Docker Inc's. version if this continues. 

We came across another bug in 1.8.2 that bit us in production: https://bugs.centos.org/view.php?id=10382, so we have a concern about Centos having  a stable version of Docker.

**Comment by abn** [comment]
@stevendborrelli did encounter that in production a couple of times; but dont think that was related to the docker version iirc, and I doubt if the 1.9 version actually fixes the root cause. The issue for us was a combination of how marathon/mesos handles container deployment and LMV/XFS kernel (that was a rabbit hole) issues. Have not had this issue recently though.

That said; I am not a big fan of how Docker Inc., handles their CentOS packaging. Would be great to see if we can strike a balance between the pros/cons?

Also, fwiw, might be better of bumping the bug at https://bugzilla.redhat.com/show_bug.cgi?id=1299519.  The fix needs to happen there first.

**Comment by stevendborrelli** [comment]
@abn what did you think the root cause was? We think it might be related to marathon killing slow docker pulls.

**Comment by abn** [comment]
@stevendborrelli that was one of the issues. I think in our case we hit 2 issues simultaneously.

Bit off-topic for the issue, however for the mesos/marathon issue, the workaround (along with some improvements was):
```yml
# mesos configuration
mesos_executor_registration_timeout: 30mins
mesos_executor_shutdown_grace_period: 60secs
mesos_docker_stop_timeout: 60secs

# marathon configuration
marathon_task_launch_timeout: 1800000
```

Which was applied in play via:
```yml
  tasks:
    - name: set mesos executor shutdown grace period
      become: yes
      copy:
        dest: /etc/mesos-slave/executor_shutdown_grace_period
        content: "{{ mesos_executor_shutdown_grace_period }}"
      tags:
        - mesos
    - name: set mesos docker stop timeout
      become: yes
      copy:
        dest: /etc/mesos-slave/docker_stop_timeout
        content: "{{ mesos_docker_stop_timeout }}"
      tags:
        - mesos
        - docker
    - name: restart mesos follower
      become: yes
      command: systemctl restart mesos-slave
      tags:
        - mesos
```

As for the second issue was the XFS lock up, see https://access.redhat.com/solutions/1521023
