### ISSUE TITLE
Move Consul TLS directory creation out of Ansible and in to RPM install

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#91]
This code block should move in to RPM install:

```
- name: create tls directory struture
  sudo: yes
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default(0700) }}"
  with_items:
    - path: /etc/consul/ssl
  when: consul_enable_tls == true
  tags:
    - consul
```

https://github.com/CiscoCloud/microservices-infrastructure/commit/ef5c4e168fa406f21ae7851ae9defdf017cbfa38
