### ISSUE TITLE
404 not found when try to access web UIs

### ISSUE THREAD

**Issue by mcapuccini** [CiscoCloud/microservices-infrastructure#934]
Hi. I successfully run terraform apply, and your provisioning playbook on my OpenStack provider. I had to repeat couple of times the ansible provisioning, maybe because services took more than expected to be loaded. However, even if the provisioning is successful when I try to access Mesos, Consul, Marathon or Chronos web UIs, I get 404 not found. The only UI that I am able to access is the Mantl one, on port 80. Checks are unknown. Is this a bug, or am I missing something? 

My terraform and ansible files follow:
```
module "dc2-keypair" {
  source = "./terraform/openstack/keypair"
  auth_url = "http://smog.uppmax.uu.se:5000/v2.0"
  tenant_id = "1c95b0311d974dbda7ef20a7514447b8"
  tenant_name = "c2015037"
  public_key = "~/.ssh/id_rsa.pub"
  keypair_name = "sshkey"
}

module "dc2-hosts-floating" {
  source = "./terraform/openstack/hosts-floating"
  auth_url = "http://smog.uppmax.uu.se:5000/v2.0"
  datacenter = "dc2"
  tenant_id = "1c95b0311d974dbda7ef20a7514447b8"
  tenant_name = "c2015037"
  control_flavor_name = "m1.medium"
  worker_flavor_name  = "m1.large"
  edge_flavor_name  = "m1.medium"
  image_name = "CentOS7"
  keypair_name = "${ module.dc2-keypair.keypair_name }"
  control_count = 3
  worker_count = 5
  edge_count = 2
  floating_pool = "ext-net"
  external_net_id = "a7a9762b-3d9e-45c8-85c5-a939b60cd0f2"
  control_data_volume_size = 20
  worker_data_volume_size = 50
}

---
# CHECK SECURITY - when customizing you should leave this in. If you take it out
# and forget to specify security.yml, security could be turned off on components
# in your cluster!
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check for security
      when: security_enabled is not defined or not security_enabled
      fail:
        msg: |
          Security is not enabled. Please run `security-setup` in the root
          directory and re-run this playbook with the `--extra-vars`/`-e` option
          pointing to your `security.yml` (e.g., `-e @security.yml`)

# BASICS - we need every node in the cluster to have common software running to
# increase stability and enable service discovery. You can look at the
# documentation for each of these components in their README file in the
# `roles/` directory, or by checking the online documentation at
# microservices-infrastructure.readthedocs.org.
- hosts: all
  vars:
    # consul_acl_datacenter should be set to the datacenter you want to control
    # Consul ACLs. If you only have one datacenter, set it to that or remove
    # this variable.
    # consul_acl_datacenter: your_primary_datacenter

    # consul_dns_domain is repeated across these plays so that all the
    # components know what information to use for this values to help with
    # service discovery.
    consul_dns_domain: consul
    consul_servers_group: role=control
  roles:
    - common
    - lvm
    - collectd
    - logrotate
    - consul-template
    - docker
    - logstash
    - nginx
    - consul
    - dnsmasq

# ROLES - after provisioning the software that's common to all hosts, we do
# specialized hosts. This configuration has two major groups: control nodes and
# worker nodes. We provision the worker nodes first so that we don't create any
# race conditions. This could happen in the Mesos components - if there are no
# worker nodes when trying to schedule control software, the deployment process
# would hang.
#
# The worker role itself has a minimal configuration, as it's designed mainly to
# run software that the Mesos leader shedules. It also forwards traffic to
# globally known ports configured through Marathon.
- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    consul_dns_domain: consul
    mesos_mode: follower
  roles:
    - mesos

# the control nodes are necessarily more complex than the worker nodes, and have
# ZooKeeper, Mesos, and Marathon leaders. In addition, they control Vault to
# manage secrets in the cluster. These servers do not run applications by
# themselves, they only schedule work. That said, there should be at least 3 of
# them (and always an odd number) so that ZooKeeper can get and keep a quorum.
- hosts: role=control
  gather_facts: no
  vars:
    consul_dns_domain: consul
    consul_servers_group: role=control
    mesos_leaders_group: role=control
    mesos_mode: leader
    zookeeper_server_group: role=control
  roles:
    - vault
    - zookeeper
    - mesos
    - marathon
    - chronos
    - mantlui

# The edge role exists solely for routing traffic into the cluster. Firewall
# settings should be such that web traffic (ports 80 and 443) is exposed to the
# world.
- hosts: role=edge
  gather_facts: no
  vars:
    # this is the domain that traefik will match on to do host-based HTTP
    # routing. Set it to a domain you control and add a star domain to route
    # traffic. (EG *.marathon.localhost)
    #
    # For those migrating from haproxy, this variable serves the same purpose
    # and format as `haproxy_domain`.
    traefik_marathon_domain: marathon.localhost
  roles:
    - traefik

# GlusterFS has to be provisioned in reverse order from Mesos: servers then
# clients.
- hosts: role=control
  gather_facts: no
  vars:
    consul_dns_domain: consul
    glusterfs_mode: server
  roles:
    - glusterfs

- hosts: role=worker
  vars:
    consul_dns_domain: consul
    glusterfs_mode: client
  roles:
    - glusterfs

```
